import {
  IconArrowUp,
  IconBooks,
  IconBrain,
  IconChefHat,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCloudDownload,
  IconCloudUpload,
  IconCpu,
  IconDatabase,
  IconDownload,
  IconHome,
  IconLogs,
  IconNotes,
  IconPlayerPlay,
  IconPlus,
  IconRefresh,
  IconRefreshAlert,
  IconRobot,
  IconSchool,
  IconSettings,
  IconTrash,
  IconUpload,
  IconWand,
  IconWorld,
  IconX,
  IconAlertTriangle,
  IconXboxX,
  IconCircleCheck,
  IconInfoCircle,
  IconBug,
  IconCopy,
  IconServer,
  IconMenu2,
  IconArrowLeft,
  IconArrowRight,
  IconSun,
  IconMoon,
  IconStethoscope,
  IconShieldCheck,
  IconTool,
  IconPlant,
  IconCode,
  IconMap,
} from '@tabler/icons-react'

/**
 * An explicit import of used icons in the DynamicIcon component to ensure we get maximum tree-shaking
 * while still providing us a nice DX with the DynamicIcon component and icon name inference.
 * Only icons that are actually used by DynamicIcon should be added here. Yes, it does introduce
 * some manual maintenance, but the bundle size benefits are worth it since we use a (relatively)
 * very limited subset of the full Tabler Icons library.
 */
export const icons = {
  IconAlertTriangle,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconBooks,
  IconBrain,
  IconBug,
  IconChefHat,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCircleCheck,
  IconCloudDownload,
  IconCloudUpload,
  IconCode,
  IconCopy,
  IconCpu,
  IconDatabase,
  IconDownload,
  IconHome,
  IconInfoCircle,
  IconLogs,
  IconMap,
  IconMenu2,
  IconMoon,
  IconNotes,
  IconPlant,
  IconPlayerPlay,
  IconPlus,
  IconRefresh,
  IconRefreshAlert,
  IconRobot,
  IconSchool,
  IconServer,
  IconSettings,
  IconShieldCheck,
  IconStethoscope,
  IconSun,
  IconTool,
  IconTrash,
  IconUpload,
  IconWand,
  IconWorld,
  IconX,
  IconXboxX
} as const

export type DynamicIconName = keyof typeof icons
